INSERT INTO prefectures (id, prefecture_name) VALUES (1, '道北');
INSERT INTO prefectures (id, prefecture_name) VALUES (2, '道東');
INSERT INTO prefectures (id, prefecture_name) VALUES (3, '道南');
INSERT INTO prefectures (id, prefecture_name) VALUES (4, '道央');
INSERT INTO prefectures (id, prefecture_name) VALUES (5, '道南');
INSERT INTO prefectures (id, prefecture_name) VALUES (6, '青森県');
INSERT INTO prefectures (id, prefecture_name) VALUES (7, '岩手県');
INSERT INTO prefectures (id, prefecture_name) VALUES (8, '宮城県');
INSERT INTO prefectures (id, prefecture_name) VALUES (9, '秋田県');
INSERT INTO prefectures (id, prefecture_name) VALUES (10, '山形県');
INSERT INTO prefectures (id, prefecture_name) VALUES (11, '福島県');
INSERT INTO prefectures (id, prefecture_name) VALUES (12, '茨城県');
INSERT INTO prefectures (id, prefecture_name) VALUES (13, '栃木県');
INSERT INTO prefectures (id, prefecture_name) VALUES (14, '群馬県');
INSERT INTO prefectures (id, prefecture_name) VALUES (15, '埼玉県');
INSERT INTO prefectures (id, prefecture_name) VALUES (16, '千葉県');
INSERT INTO prefectures (id, prefecture_name) VALUES (17, '東京都');
INSERT INTO prefectures (id, prefecture_name) VALUES (18, '神奈川県');
INSERT INTO prefectures (id, prefecture_name) VALUES (19, '新潟県');
INSERT INTO prefectures (id, prefecture_name) VALUES (20, '富山県');
INSERT INTO prefectures (id, prefecture_name) VALUES (21, '石川県');
INSERT INTO prefectures (id, prefecture_name) VALUES (22, '福井県');
INSERT INTO prefectures (id, prefecture_name) VALUES (23, '山梨県');
INSERT INTO prefectures (id, prefecture_name) VALUES (24, '長野県');
INSERT INTO prefectures (id, prefecture_name) VALUES (25, '岐阜県');
INSERT INTO prefectures (id, prefecture_name) VALUES (26, '静岡県');
INSERT INTO prefectures (id, prefecture_name) VALUES (27, '愛知県');
INSERT INTO prefectures (id, prefecture_name) VALUES (28, '三重県');
INSERT INTO prefectures (id, prefecture_name) VALUES (29, '滋賀県');
INSERT INTO prefectures (id, prefecture_name) VALUES (30, '京都府');
INSERT INTO prefectures (id, prefecture_name) VALUES (31, '大阪府');
INSERT INTO prefectures (id, prefecture_name) VALUES (32, '兵庫県');
INSERT INTO prefectures (id, prefecture_name) VALUES (33, '奈良県');
INSERT INTO prefectures (id, prefecture_name) VALUES (34, '和歌山県');
INSERT INTO prefectures (id, prefecture_name) VALUES (35, '鳥取県');
INSERT INTO prefectures (id, prefecture_name) VALUES (36, '島根県');
INSERT INTO prefectures (id, prefecture_name) VALUES (37, '岡山県');
INSERT INTO prefectures (id, prefecture_name) VALUES (38, '広島県');
INSERT INTO prefectures (id, prefecture_name) VALUES (39, '山口県');
INSERT INTO prefectures (id, prefecture_name) VALUES (40, '徳島県');
INSERT INTO prefectures (id, prefecture_name) VALUES (41, '香川県');
INSERT INTO prefectures (id, prefecture_name) VALUES (42, '愛媛県');
INSERT INTO prefectures (id, prefecture_name) VALUES (43, '高知県');
INSERT INTO prefectures (id, prefecture_name) VALUES (44, '福岡県');
INSERT INTO prefectures (id, prefecture_name) VALUES (45, '佐賀県');
INSERT INTO prefectures (id, prefecture_name) VALUES (46, '長崎県');
INSERT INTO prefectures (id, prefecture_name) VALUES (47, '熊本県');
INSERT INTO prefectures (id, prefecture_name) VALUES (48, '大分県');
INSERT INTO prefectures (id, prefecture_name) VALUES (49, '宮崎県');
INSERT INTO prefectures (id, prefecture_name) VALUES (50, '鹿児島県');
INSERT INTO prefectures (id, prefecture_name) VALUES (51, '沖縄県');

INSERT INTO cities (id, city_name, prefecture_id) VALUES ('011000', '稚内', 1);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('012010', '旭川', 1);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('012020', '留萌', 1);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('013010', '網走', 2);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('013020', '北見', 2);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('013030', '紋別', 2);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('014010', '根室', 2);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('014020', '釧路', 2);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('014030', '帯広', 2);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('015010', '室蘭', 3);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('015020', '浦河', 3);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('016010', '札幌', 4);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('016020', '岩見沢', 4);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('016030', '倶知安', 4);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('017010', '函館', 5);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('017020', '江差', 5);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('020010', '青森', 6);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('020020', 'むつ', 6);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('020030', '八戸', 6);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('030010', '盛岡', 7);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('030020', '宮古', 7);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('030030', '大船渡', 7);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('040010', '仙台', 8);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('040020', '白石', 8);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('050010', '秋田', 9);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('050020', '横手', 9);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('060010', '山形', 10);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('060020', '米沢', 10);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('060030', '酒田', 10);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('060040', '新庄', 10);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('070010', '福島', 11);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('070020', '小名浜', 11);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('070030', '若松', 11);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('080010', '水戸', 12);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('080020', '土浦', 12);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('090010', '宇都宮', 13);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('090020', '大田原', 13);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('100010', '前橋', 14);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('100020', 'みなかみ', 14);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('110010', 'さいたま', 15);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('110020', '熊谷', 15);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('110030', '秩父', 15);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('120010', '千葉', 16);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('120020', '銚子', 16);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('120030', '館山', 16);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('130010', '東京', 17);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('130020', '大島', 17);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('130030', '八丈島', 17);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('130040', '父島', 17);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('140010', '横浜', 18);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('140020', '小田原', 18);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('150010', '新潟', 19);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('150020', '長岡', 19);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('150030', '高田', 19);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('150040', '相川', 19);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('160010', '富山', 20);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('160020', '伏木', 20);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('170010', '金沢', 21);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('170020', '輪島', 21);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('180010', '福井', 22);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('180020', '敦賀', 22);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('190010', '甲府', 23);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('190020', '河口湖', 23);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('200010', '長野', 24);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('200020', '松本', 24);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('200030', '飯田', 24);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('210010', '岐阜', 25);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('210020', '高山', 25);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('220010', '静岡', 26);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('220020', '網代', 26);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('220030', '三島', 26);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('220040', '浜松', 26);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('230010', '名古屋', 27);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('230020', '豊橋', 27);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('240010', '津', 28);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('240020', '尾鷲', 28);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('250010', '大津', 29);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('250020', '彦根', 29);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('260010', '京都', 30);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('260020', '舞鶴', 30);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('270000', '大阪', 31);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('280010', '神戸', 32);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('280020', '豊岡', 32);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('290010', '奈良', 33);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('290020', '風屋', 33);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('300010', '和歌山', 34);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('300020', '潮岬', 34);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('310010', '鳥取', 35);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('310020', '米子', 35);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('320010', '松江', 36);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('320020', '浜田', 36);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('320030', '西郷', 36);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('330010', '岡山', 37);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('330020', '津山', 37);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('340010', '広島', 38);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('340020', '庄原', 38);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('350010', '下関', 39);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('350020', '山口', 39);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('350030', '柳井', 39);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('350040', '萩', 39);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('360010', '徳島', 40);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('360020', '日和佐', 40);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('370000', '高松', 41);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('380010', '松山', 42);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('380020', '新居浜', 42);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('380030', '宇和島', 42);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('390010', '高知', 43);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('390020', '室戸岬', 43);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('390030', '清水', 43);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('400010', '福岡', 44);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('400020', '八幡', 44);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('400030', '飯塚', 44);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('400040', '久留米', 44);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('410010', '佐賀', 45);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('410020', '伊万里', 45);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('420010', '長崎', 46);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('420020', '佐世保', 46);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('420030', '厳原', 46);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('420040', '福江', 46);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('430010', '熊本', 47);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('430020', '阿蘇乙姫', 47);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('430030', '牛深', 47);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('430040', '人吉', 47);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('440010', '大分', 48);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('440020', '中津', 48);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('440030', '日田', 48);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('440040', '佐伯', 48);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('450010', '宮崎', 49);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('450020', '延岡', 49);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('450030', '都城', 49);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('450040', '高千穂', 49);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('460010', '鹿児島', 50);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('460020', '鹿屋', 50);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('460030', '種子島', 50);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('460040', '名瀬', 50);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('471010', '那覇', 51);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('471020', '名護', 51);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('471030', '久米島', 51);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('472000', '南大東', 51);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('473000', '宮古島', 51);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('474010', '石垣島', 51);
INSERT INTO cities (id, city_name, prefecture_id) VALUES ('474020', '与那国島', 51);
